// Generated by uniffi-bindgen-react-native
#include "lwk-rn.h"
#include "generated/lwk.hpp"

namespace lwkrn {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeLwk::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}