// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "lwk-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNLwkRnSpec.h"

@interface LwkRn : NSObject <NativeLwkRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface LwkRn : NSObject <RCTBridgeModule>
#endif

@end